language: go
go:
- 1.12.x
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
before_install:
- chmod +x ./sonar.sh
script:
- make lint
- make test
- "./sonar.sh"
after_script:
- make cover
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud: true
env:
  global:
  - secure: OqDAwMmA+zcDuLhKl9lE5fVVJxFJMbrooa1UnPyQ+18rX5slIZzP8n5dHO03FLL2XKr+e32TJ2XuwsUVSW+wI4p5BwrM2T93sKlWr+waBYBfm2rVqK41t9oEKSK4W6DpiM6h/G53RzBwLbm6OMr18r6vSr+apT8zA5lXIUKNaLZOB8dRtxpFst5OLAR0nhAngsFqk6A83yBglABCZXfZXF7Wuer2IKObxEFr2wO+aP6alapGN5ZTvsRJJzsz1S9hiwWrmeGS8srXJNVaQHVJPSKTCMdcDb90XtqMoj8z/Avxq+7uxKY7i+kngOPkqk2JpisTLR664pik/cU6xtWH+/sAIJYxmh8oDucTRuVQkb30tRbths+hUFtU5Cwt5BlbkWzHJbgf8IQEzuLRackjIMfXJWXf2bof08hKHyWD1jSkMQIq6pT/GkoRVKIn+e1s7A4MBmokG+Q+gaTxs85jcO0da3Div2BULQBvD9tI2ryEYW7BwFU8IhJ5keszVFCcA7J24Lc9S/6ToXNxI6hW9BMff7vlG5kFVC7CXoM+fbnxzZiNmyh6MfrO2QjVUFjQJPkUaYl9hzQtWlipbeI3x1Dpr5IBMRn3u67digA2FMvtkYZgBXipUETkbUIa5oUndCtCTV5RZx18/YQReTy4ehlyxUKkac1UzT9Hls11XG0=
  - secure: eriMZw5TyYuXbaFtxoEkD7u4kfXESXRl1t8X0WrS+3FnT0p2/vWdb5Hy2hC7RPAaZREiS2BJC3YYbFcMwuJkekwKSAf9/cGmaaWy+cnSnpBcVQiIn7TIpOLCGQZRiUCq/vvnp4YEdgX/LXF/5Vq/3M8U7f+r8wTuYmLMtptx3+32CD4AFoWJ69hRTfyUUKCoy+j4pDAyUvtOAPecrRU3pPnkXqz5PEuqzdx3oNsCwe7LqXsPUeo8l0gD6r/HrAMHFiSVTWkiwokUvp36wmGR768ZA+M1bKLyBD76Y7j9B6orvEYFfgC+EdhCcE8l/sYfGJwwX2FHJhFK9AcQthLk9Hfkzw/bNs5Fd4L4cp664xhAFTNXFhJFH4p8vGRpCH8Mf8MlzAGjZUEh4poBNKWl/FhrRfN6WsI9GmMYwPBegax6NqMURqZ5ZqcXbEFZ5dJURrnFNUC3oN2BPUqI9+5c3cwfJflmQpnuPVuiau2L5g3+WVlJfdIvTkLx+P6SW2BGqYm6pJoAihcXYe59Sac9Pb1dF2V/u9KtONnPgsJLkksTSL32YjQ5BfF0Yh7bUi1G5ItKOgS+MLLhwcGSvwYmbtWWt5o4cMxoV8Ds7pjFu6Lw0FlrGEeb1j0fOOafJLOcnR9pyEglX0KfTsrxxAy86PEbv/dOeM3f7az86+Qk//Y=
  - secure: WZ5N7rtkDpKV1ldZi6sezc6WMc7DPCNWWd/svd7hdUAjGL6ywPHDIiYt/WzEFc7nYGUyQesyVnFIQHxO46nphPsPA60japvfLSShI54QL5+mkRg6QdkVD4Tjh6sIdud0cDXFXLafr3K9nP15XwDyW0gsQN4vi70Vc1j/EH8myc9Tc2RgUpxzJUROrwTq9W1DtvWpvOr1Hx5cT0GK3ShdLwWE/TUshpo1q3rSCR8nN52ahanEXayllkfTR6hfHsQ1ICyPXuY2LrUgtQu8fLf3VpaCIDKmRPzfcZZF2tad5UA0wRcBwCLex8JPExtzu9impGEilDfbZadrw85BPH8TtDvrkHG/pkmlDr8dBOvH66XVW9IVnYTlb9mSyOPvPnFASxdLkn6cl4m/+IXx1pXAN0Xg9lwXvQnJ8T5MPL3f/K1JVFRouBGLLbaaTisZURqNWkErFNw23FLEd7wiU8Vdo2Zp9qSLEdnhiRDAMkGE4DxlamWfhLgCboKgYftv4N0G8aqECwVk+wg/bwhl0ObgWnq+5B7L1VjCUImD28YbpDdJVaeA31ma/+ap1OMVAyEBG4KaOSIi3Vv5NvdfsQv8/dfNJrLekHIhL8RiHcnOLtmkqQuNFMb0n85MYSaBqp+LYAm+aUjEzbzkCkNqwKjwCdO3MLbNbC/8zUPx6p2PmYY=
  - secure: NA/G0n02YmJzYL+sXEQJEAiUkebvKMjfh+aOtl9ExxAE/BRnHAy84LKyB2HFROjssA+ho4rD53MO6kqsP6shKlw3pRVqEdOdSOUIi/BScL8/zA2FiXfrdUXSNeegQfCjGRPOswwyD31B1EIGqzLFH5eJJsHLcPvJ94Xmy8Oe1nIqxb+JOxh0Q+nDTdMr+c0s8m0CBWp0Qja5O42OjHjGGIpjbWXQf4cSi3gcSsuSPSSpNQ66pV/at4jPWX+Ts/tQGCMPWK1vPK+7qiqb2yxWmRJYo8BB0p1QXJVKvhL6Yzzb6mQPl3Ke/vWirGEMywa7Ckb0vHB8sPfkqcDcngfCLIr8zFhyMuJvwWSlAfIPiAPToabzadQe5nB7+Spr2HfunJZDbp36q8livug/q07oRY0tvPy+C8tOeKtgbJ5nJ65DFiDoRarNuhGqXbpwkMOpPBNq+zgbyWcimnsMMIKuKBFru211hQCobkWI7zsGxyGcwbBdAJzesa0/SuPXTbagF49ZakLMw2k7Av7cZru9iIFmA5oiBrCwAXjY1+R7/llEuB/HyRHk/siNLdFNUebeu6n4yTjH1eLCPedrgab8M0lGEWDaH9iX5Rp71dSdyd93oPSNVyqWYMU8SN2VBOAgaQghb7Cd0Ml+m5d3cd0PxjKud3loEsMa74UfMf7nb3E=
  - GO111MODULE=on
